server:
  port: 12000
spring:
  application:
    name: tensquare-config
  cloud:
    config:
      server:
        git:
          uri: http://192.168.135.132:3000/Yu/configee.git
#  rabbitmq:
#    host: 192.168.135.132
#management:
#  endpoints:
#    web:
#      exposure:
#        include: bus-refresh